export const dubaiNowItems = [
  {
    slug: 'volunteer',
    slug_en: 'volunteer',
    slug_ar: 'التطوع',
    en: 'Volunteer',
    ar: 'التطوع',
    videoSrc: '',
  },
  {
    slug: 'domestic-workers',
    slug_en: 'domestic-workers',
    slug_ar: 'العمالة-المنزلية',
    en: 'Domestic Workers',
    ar: 'العمالة المنزلية',
    videoSrc:
      'https://player.vimeo.com/video/1126221661?h=29587f9209&badge=0&autopause=0&player_id=0&app_id=58479&autoplay=1&muted=1&loop=1',
  },
  {
    slug: 'marriage',
    slug_en: 'marriage',
    slug_ar: 'الزواج',
    en: 'Marriage',
    ar: 'الزواج',
    videoSrc: '',
  },
  {
    slug: 'rent-a-home',
    slug_en: 'rent-a-home',
    slug_ar: 'استئجار-منزل',
    en: 'Rent a Home',
    ar: 'استئجار منزل',
    videoSrc: '',
  },
  {
    slug: 'may-they-rest-in-peace',
    slug_en: 'may-they-rest-in-peace',
    slug_ar: 'إكرام-الموتى',
    en: 'May They Rest In Peace',
    ar: 'إكرام الموتى',
    videoSrc: '',
  },
  {
    slug: 'obtain-medical-id',
    slug_en: 'obtain-medical-id',
    slug_ar: 'الحصول-على-الهوية-الطبية',
    en: 'Obtain Medical ID',
    ar: 'الحصول على الهوية الطبية',
    videoSrc: '',
  },
  {
    slug: 'get-married',
    slug_en: 'get-married',
    slug_ar: 'عقد-الزواج',
    en: 'Get Married',
    ar: 'عقد الزواج',
    videoSrc: '',
  },
  {
    slug: 'get-family-house',
    slug_en: 'get-family-house',
    slug_ar: 'الحصول-على-سكن-عائلي',
    en: 'Get Family House',
    ar: 'الحصول على سكن عائلي',
    videoSrc: '',
  },
  {
    slug: 'land-exchange',
    slug_en: 'land-exchange',
    slug_ar: 'استبدال-الأراضي',
    en: 'Land Exchange',
    ar: 'استبدال الأراضي',
    videoSrc: '',
  },
  {
    slug: 'electric-vehicle',
    slug_en: 'electric-vehicle',
    slug_ar: 'مركبة-كهربائية',
    en: 'Electric Vehicle',
    ar: 'مركبة كهربائية',
    videoSrc: '',
  },
  {
    slug: 'buy-and-sell-property',
    slug_en: 'buy-and-sell-property',
    slug_ar: 'بيع-وشراء-العقارات',
    en: 'Buy and Sell Property',
    ar: 'بيع وشراء العقارات',
    videoSrc: '',
  },
];
