export const dubaiNowItems = [
  {
    slug: 'volunteer',
    slug_en: 'volunteer',
    slug_ar: 'التطوع',
    en: 'Volunteer',
    ar: 'التطوع',
    videoSrc_en: 'https://player.vimeo.com/video/1126585437?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126585556?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'domestic-workers',
    slug_en: 'domestic-workers',
    slug_ar: 'العمالة-المنزلية',
    en: 'Domestic Workers',
    ar: 'العمالة المنزلية',
    videoSrc_en: 'https://player.vimeo.com/video/1126583090?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126586137?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'marriage',
    slug_en: 'marriage',
    slug_ar: 'الزواج',
    en: 'Marriage',
    ar: 'الزواج',
    videoSrc_en: 'https://player.vimeo.com/video/1126583160?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126583302?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'rent-a-home',
    slug_en: 'rent-a-home',
    slug_ar: 'استئجار-منزل',
    en: 'Rent a Home',
    ar: 'استئجار منزل',
    videoSrc_en: 'https://player.vimeo.com/video/1126585875?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126585674?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'may-they-rest-in-peace',
    slug_en: 'may-they-rest-in-peace',
    slug_ar: 'إكرام-الموتى',
    en: 'May They Rest In Peace',
    ar: 'إكرام الموتى',
    videoSrc_en: 'https://player.vimeo.com/video/1126579896?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126579974?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'obtain-medical-id',
    slug_en: 'obtain-medical-id',
    slug_ar: 'الحصول-على-الهوية-الطبية',
    en: 'Obtain Medical ID',
    ar: 'الحصول على الهوية الطبية',
    videoSrc_en: 'https://player.vimeo.com/video/1126579878?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126579303?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'get-married',
    slug_en: 'get-married',
    slug_ar: 'عقد-الزواج',
    en: 'Get Married',
    ar: 'عقد الزواج',
    videoSrc_en: 'https://player.vimeo.com/video/1126583160?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126583302?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'get-family-house',
    slug_en: 'get-family-house',
    slug_ar: 'الحصول-على-سكن-عائلي',
    en: 'Get Family House',
    ar: 'الحصول على سكن عائلي',
    videoSrc_en: 'https://player.vimeo.com/video/1126583529?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126583675?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'land-exchange',
    slug_en: 'land-exchange',
    slug_ar: 'استبدال-الأراضي',
    en: 'Land Exchange',
    ar: 'استبدال الأراضي',
    videoSrc_en: 'https://player.vimeo.com/video/1126583471?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126583494?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'electric-vehicle',
    slug_en: 'electric-vehicle',
    slug_ar: 'مركبة-كهربائية',
    en: 'Electric Vehicle',
    ar: 'مركبة كهربائية',
    videoSrc_en: 'https://player.vimeo.com/video/1126583043?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126583068?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
  {
    slug: 'buy-and-sell-property',
    slug_en: 'buy-and-sell-property',
    slug_ar: 'بيع-وشراء-العقارات',
    en: 'Buy and Sell Property',
    ar: 'بيع وشراء العقارات',
    videoSrc_en: 'https://player.vimeo.com/video/1126580169?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
    videoSrc_ar: 'https://player.vimeo.com/video/1126580059?title=0&byline=0&portrait=0&badge=0&autopause=0&app_id=58479',
  },
];
