export const RedirectBase = [
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Dubai AI",
    app: "Dubai Now",
    orientation: "Vertical",
    screen: "Screen 1",
    screenTitle: "Dubai AI",
    link: "dubaiNowQA://success",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Digital Assistant",
    app: "Smart Employee",
    orientation: "Vertical",
    screen: "Screen 2",
    screenTitle: "Employee Digital Assistant",
    link: "smartemployeeQA://success",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Recruitment Agents",
    app: "Smart Employee",
    orientation: "Horizontal",
    screen: "Screen 3",
    screenTitle: "AI Agent as a service",
    link: "smartemployeeQA://success",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Sourcing Agents",
    app: "Smart Supplier",
    orientation: "Vertical",
    screen: "Screen 3",
    screenTitle: "Smart Supplier",
    link: "SmartSupplier://",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Procurement & Contract Agent",
    app: "Smart Employee",
    orientation: "Horizontal",
    screen: "Screen 3",
    screenTitle: "Procurement & Contract Agent",
    link: "smartemployeeQA://success",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "AI Committee as a service",
    app: "Portal",
    orientation: "Horizontal",
    screen: "Screen 4",
    screenTitle: "AI Committee as a service",
    link: "waiting for link",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Product Co pilot",
    app: "Portal",
    orientation: "Horizontal",
    screen: "Screen 5",
    screenTitle: "Product Copilot",
    link: "waiting for link",
  },
  {
    entity: "DDGE / Tunnel Left Side",
    project: "Dubai Government AI Infrastructure Platform",
    app: "Presentation",
    orientation: "Horizontal",
    screen: "Screen 6",
    screenTitle: "Dubai Government AI Infrastructure Platform",
    link: "waiting for presentation",
  },
];